version: '3.9'

services:
  quick-solution-postgres-container:
    image: postgres
    restart: always
    container_name: quick-solution-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase

    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - delivery-network

volumes:
  db_data:
networks:
  delivery-network:
    driver: bridge
