CREATE TABLE Users(
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar(100) not null,
                      email varchar(100) not null UNIQUE,
                      password varchar(100) not null,
                      type varchar(50) DEFAULT 'ROLE_USER'
);
CREATE TABLE Orders(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       users_id int references Users(id) on delete cascade,
                       date timestamp NOT NULL,
                       name varchar(100),
                       status varchar(100) DEFAULT 'registered'
--     delivery_id int UNIQUE REFERENCES Delivery(id) добавляется позже
);
create table Delivery(
                         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         order_id int UNIQUE REFERENCES orders(id) on delete cascade,
                         start_address varchar(100) not null,
                         finish_address varchar(100) not null,
                         courier_id int,
                         status varchar(100) DEFAULT 'in processing',
                         coordinates point not null
);


alter table orders add column delivery_id int UNIQUE REFERENCES Delivery(id);

create table courierInf(
                           id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id int UNIQUE REFERENCES users(id) on delete cascade,
                           status varchar(100) default 'free'
);